version: "3.2"

services:
  selenoid:
    network_mode: "bridge"
    image: aerokube/selenoid:latest-release
    ports:
      - "4444:4444"
    volumes:
      - "./selenoid:/etc/selenoid"
    command: ["-conf", "/etc/selenoid/browsers.json"]

#  test_runner:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: tests_run
#    container_name: tests_works
#    network_mode: "host"
#    volumes:
#      - type: bind
#        source: .bind
#        target: /bind/