version: "3"

services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    ports:
      - "4440:4444"
    logging:
      driver: local

  test_runner:
    build:
      context: .
      dockerfile: Dockerfile
    image: tests_run
    container_name: tests_works
    network_mode: "host"